### ISSUE TITLE
no data is read from the Oracle database.

### ISSUE THREAD

**Issue by Frank79240** [mhertzfeld/CrystalReportsNinja#11]
Hello,
The reader of my state works as well as the connection to the database Oracle. I change the password or the user and I have a connection error.
I do tests with or without parameters and by modifying my printing state and in any case no data is read in the Oracle database.
Thank you for your help, cordially.

**Comment by mhertzfeld** [comment]
I'm not sure if I am understanding the problem you are describing.

Are you saying that you can run ninja ok with a specific user, but when you change to another user you are having connection issues to the DB?  Or are you saying you cannot connect to the DB at all using Ninja?

I'm assuming you are able to connect to the DB ok in the developer?

**Comment by Frank79240** [comment]
Bonjour et merci de votre réponse,
Le changement d'utilisateur et de mot de passe est un test pour vérifier que la connexion est OK.
Mon probléme est que l'application Ninja ne retourne aucune erreur, mais l'édition de l'état n'affiche aucune donnée (Feuille blanche)

Fichier .log
"30-09-2019	08:44:28	instantiated
30-09-2019	08:44:28	Report loaded successfully
30-09-2019	08:44:28	Logon to Server = xxxxxxx
30-09-2019	08:44:28	Logon with user id = XXXXX
30-09-2019	08:44:28	Logon with password = yyyyyy
30-09-2019	08:44:29	Discrete Parameter : numdeb = OFR00001
30-09-2019	08:44:29	Discrete Parameter : numfin = OFR00001
30-09-2019	08:44:29	Discrete Parameter : typedoc = 1
30-09-2019	08:44:35	Report printed to : Microsoft Print to PDF"

Cordially.

**Comment by Frank79240** [comment]
Hello and thank you for your answer,
The change of user and password is a test to verify that the connection is OK.
My problem is that the Ninja application does not return any errors, but the state edition does not display any data (Blank sheet)

Fichier .log
"30-09-2019	08:44:28	instantiated
30-09-2019	08:44:28	Report loaded successfully
30-09-2019	08:44:28	Logon to Server = xxxxxxx
30-09-2019	08:44:28	Logon with user id = XXXXX
30-09-2019	08:44:28	Logon with password = yyyyyy
30-09-2019	08:44:29	Discrete Parameter : numdeb = OFR00001
30-09-2019	08:44:29	Discrete Parameter : numfin = OFR00001
30-09-2019	08:44:29	Discrete Parameter : typedoc = 1
30-09-2019	08:44:35	Report printed to : Microsoft Print to PDF"

Cordially.

**Comment by mhertzfeld** [comment]
Check to make sure that the version of Ninja (64bit\32bit) matches the ODBC Driver (64bit\32bit) that you are using.  From what I understand the Crystal Developer is still 32bit so you are probably using a 32bit ODBC Driver with it.  So check to make sure you are using the 32bit version of Ninja, or switch your ODBC DSN to the 64bit version of the ODBC Driver.

**Comment by mhertzfeld** [comment]
No update in over a month.  Closing issue.
