### ISSUE TITLE
Missing parameter values

### ISSUE THREAD

**Issue by mikecrf121** [mhertzfeld/CrystalReportsNinja#14]
Hi,
Im running into a lot of missing parameters error when trying to run and execute these reports, is their any way we can get a log of which params are missing? that would help ALOT

**Comment by mikecrf121** [comment]
What i really need is a way for default parameters be used(within the actual .rpt file) when no parameter is specified, any thoughts or guidance for this would be greatly appreciated.

**Comment by fabian-sta** [comment]
> Hi,
> Im running into a lot of missing parameters error when trying to run and execute these reports, is their any way we can get a log of which params are missing? that would help ALOT

Try the latest update as I added extra logging in terms of parameter counts, names, type and if they are excluded due to linking.

**Comment by mhertzfeld** [comment]
@fabian-sta has added the requested logging.  Closing.
