### ISSUE TITLE
Printing Issue

### ISSUE THREAD

**Issue by fabian-sta** [mhertzfeld/CrystalReportsNinja#16]
Been working on the code you have released in this branch as its the closest to whet we need.
However Printing is only ever printig to the default printer

CrystalReportsNinja.exe -LC -S SERVER -U USER -P PASS-D Database-E print -N test -F report.rpt " -a Year:2019 -a Month:09 "

Output is Report printed to : (BLANK) and prints to the default printer.

**Comment by fabian-sta** [comment]
**Found the issue was related to the RPT File Page Setup / No Printer Option**
The "No Printer (optimized for screen display) was enabled
With this set it ignored the specified printer and just printed to the windows default printer.

May need to resolve this, as reports could start printing anywhere

**Comment by mhertzfeld** [comment]
ok.  I will see what I can find out.

Good work on finding the optimized for screen display option is causing the problem.

**Comment by fabian-sta** [comment]
This issue has been resolved
added the _reportDoc.PrintOptions.NoPrinter = false; line into the ReportProcessor.cs file
Has been added to a fork waiting a PULL request.
[Printer Section.txt](https://github.com/mhertzfeld/CrystalReportsNinja/files/3812162/Printer.Section.txt)
