### ISSUE TITLE
Fehler beim Laden der Datenbankinformationen

### ISSUE THREAD

**Issue by hdrexel** [mhertzfeld/CrystalReportsNinja#2]
Exception: Fehler in der Datei Bericht1 10828_8852_{3FA216C5-228E-41C1-AC1E-D3BECFBA20B2}.rpt:
Fehler beim Laden der Datenbankinformationen
Inner Exception: System.Runtime.InteropServices.COMException (0x800002CD): Fehler in der Datei Bericht1 10828_8852_{3FA216C5-228E-41C1-AC1E-D3BECFBA20B2}.rpt:
Fehler beim Laden der Datenbankinformationen
   bei CrystalDecisions.ReportAppServer.Controllers.ReportSourceClass.Export(ExportOptions pExportOptions, RequestContext pRequestContext)
   bei CrystalDecisions.ReportSource.EromReportSourceBase.ExportToStream(ExportRequestContext reqContext)

Any help

**Comment by mhertzfeld** [comment]
Can't read the error.

Which version of Crystal Runtime do you have installed?  Are you running 64 or 32bit?

**Comment by mhertzfeld** [comment]
Closing issue.
