### ISSUE TITLE
Export to CSV prints header line on each row

### ISSUE THREAD

**Issue by yois615** [mhertzfeld/CrystalReportsNinja#20]
This is a known issue already:

https://apps.support.sap.com/sap/support/knowledge/public/en/1817212

How can this issue be remedied with this incredible tool?  How can I programmatically "check the box" to "Isolate Report/Page sections"

**Comment by fabian-sta** [comment]
Looks like there is an option for this but I'm not sure how and where to add

namespace CrystalDecisions.Shared
{
    public enum CsvExportSectionsOption
    {
        Export = 0,
        ExportIsolated = 1,
        DoNotExport = 2
    }
}

**Comment by yois615** [comment]
Where did you find that?  I would try to add here:
https://github.com/mhertzfeld/CrystalReportsNinja/blob/8836ba0e3e15d6abbc2c8968a2fe81df5c1af9ca/Source/CrystalReportsNinja/ReportProcessor.cs#L244

**Comment by fabian-sta** [comment]
Done!!
                else if (_outputFormat.ToUpper() == "CSV")
                {
                    CharacterSeparatedValuesFormatOptions csvExpOpts = new CharacterSeparatedValuesFormatOptions();
                    csvExpOpts.ExportMode = CsvExportMode.Standard;
                    csvExpOpts.GroupSectionsOption = CsvExportSectionsOption.Export;
                    csvExpOpts.ReportSectionsOption = CsvExportSectionsOption.Export;
                    csvExpOpts.GroupSectionsOption = CsvExportSectionsOption.ExportIsolated;
                    csvExpOpts.ReportSectionsOption = CsvExportSectionsOption.ExportIsolated;
                    csvExpOpts.SeparatorText = ",";
                    csvExpOpts.Delimiter = "\"";
                    _reportDoc.ExportOptions.ExportFormatType = ExportFormatType.CharacterSeparatedValues;
                    _reportDoc.ExportOptions.FormatOptions = csvExpOpts;
                }
                else if (_outputFormat.ToUpper() == "PDF")

**Comment by mhertzfeld** [comment]
@yois615 did this fix the problem you were having?

**Comment by yois615** [comment]
Yes it did, thanks for the recompilation as well, saving me a couple of minutes.
