### ISSUE TITLE
Exception: Invalid printer specified

### ISSUE THREAD

**Issue by skellerggh** [mhertzfeld/CrystalReportsNinja#24]
Receiving error "Exception: Invalid Crystal Reports File Inner Exception:" 

-F Reports\OR Surgery Schedule_Tomorrow.rpt

Windows Server 2012 R2 
.NET 4.8
Crystal Reports runtime engine .NET 13.0.5

Crystal report path and name is correct. This is working on one of our legacy systems.

**Comment by mhertzfeld** [comment]
Start by uninstalling the Crystal Reports Runtime 13.0.5 and installing Crystal Reports Runtime 13.0.24 and let me know how that goes.  I would suggest installing both 32bit and 64bit runtimes, there should be no conflict.

Are you using ODBC DSNs in your report?  Crystal Developer is a 32bit app that will use the 32bit DSNs.  If you choose to run the 64bit Ninja, make sure you have 64bit DSNs defined, a lot of people overlook that.

**Comment by skellerggh** [comment]
Thank you for the quick reply. 

I installed 13.0.2.469 and still receive the same error. I will try the ODBC DSN change you mentioned. Can you please point me where this change is made? I am using the 64bit version of Ninja. 

Thanks!

**Comment by skellerggh** [comment]
Hello, 

Made some progress. I have been able to get past the "Exception: Invalid Crystal Reports File Inner Exception" but now get stuck with an "Invalid printer specified". 

The parameter used (which also works on our other server).

-N \\printserver1\ITP6

Any ideas? 

THanks again!

**Comment by fabian-sta** [comment]
Looks like you may not have the drivers for that printer instaled on the server you are running the report on.
First add the Network printer to wWindows and make sure you can print to it. Once that is done you can go ahead and delete the printer but keep the drivers as thats all that is required.

also printer should be double backslash
-N \\printserver1\ITP6

**Comment by mhertzfeld** [comment]
@skellerggh did this resolve your issue?

**Comment by skellerggh** [comment]
Sorry, I meant to reply earlier. It looks like two things fixed this issue.

1)  Installing Crystal Reports Runtime 13.0.24 both 32 and 64 bit versions
2) Updating printer parameter -N to include the correct print server. For some reason this was not something that I needed to update on our other server. 

Thank you for the help you provided! 
Steve
