### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by Zolous** [mhertzfeld/CrystalReportsNinja#26]
Invoked with the following cmd call
`CrystalReportsNinja.exe -U user1 -P password -S server -F C:\CrystalReportsNinja\64-bit
\test.rpt -O C:\CrystalReportsNinja\64-bit\test1.pdf -E pdf -a "filter_id:80742"`

producing the following log
[ninja-20200204171133.log](https://github.com/mhertzfeld/CrystalReportsNinja/files/4156401/ninja-20200204171133.log)

Using SAP Runtime 64 bit build v13.0.26.3348

**Comment by fabian-sta** [comment]
You don’t have your Date attribute defined!

**Comment by Zolous** [comment]
That parameter wasn't being utilized, so I removed it from the .rpt file and am still receiving the same error.

[ninja-20200204172243.log](https://github.com/mhertzfeld/CrystalReportsNinja/files/4156424/ninja-20200204172243.log)

**Comment by fabian-sta** [comment]
Just realized you haven't specified the Database to use in your command
CrystalReportsNinja.exe -U user1 -P password -S server **-D DATABSENAME** -F C:\CrystalReportsNinja\64-bit \test.rpt -O C:\CrystalReportsNinja\64-bit\test1.pdf -E pdf -a "filter_id:80742"

**Comment by Zolous** [comment]
That should be an optional requirement as it is the default DB connection, but directly providing it yields the exact same error.

**Comment by fabian-sta** [comment]
Possibly due to your Crystl Runtmie version as this has been setup and tested to run SAP Runtime 64 bit build v13_0_25

What version SAP are you using?
This works with SAP9.3 PL12

**Comment by Zolous** [comment]
I'll try downgrading my runtime to 13.0.25 tomorrow and see how that holds.
As per the SAP version, and assuming I'm understanding the question correctly; I'm not attempting to utilize this with SAP Business one. 

Attempting to run this against a report with no datasource , and no parameters yields a similar error, but at a different section.

[error.log](https://github.com/mhertzfeld/CrystalReportsNinja/files/4156699/error.log)

**Comment by fabian-sta** [comment]
How did you go after you downgraded the Runtime

**Comment by mhertzfeld** [comment]
No reply in over a month.  Closing issue.
