### ISSUE TITLE
Unable to output

### ISSUE THREAD

**Issue by charlesgroce** [mhertzfeld/CrystalReportsNinja#29]
Hi there,

I've been banging my head on the wall trying to figure this out.  Below is the log for a very simple output job.  Authentication works fine, it sees the report, I elected no output select (so it defaults to text). I've verified the report runs in the studio environment without error.  I'm at a loss as to what's going on.  Anything you could do to help would be amazing!

Running Crystal Runtime 13.0.27 64-bit on Windows 10 64-bit. 

--

04-08-2020	16:13:28	===================Logs and Errors =================================
04-08-2020	16:13:28	Message: Object reference not set to an instance of an object.
04-08-2020	16:13:28	HResult: -2147467261
04-08-2020	16:13:28	Data: System.Collections.ListDictionaryInternal
04-08-2020	16:13:28	Inner Exception: 
04-08-2020	16:13:28	StackTrace:    at CrystalDecisions.CrystalReports.Engine.FormatEngine.ExportToStream(ExportRequestContext reqContext)
   at CrystalDecisions.CrystalReports.Engine.FormatEngine.Export(ExportRequestContext reqContext)
   at CrystalDecisions.CrystalReports.Engine.FormatEngine.Export()
   at CrystalDecisions.CrystalReports.Engine.ReportDocument.Export()
   at CrystalReportsNinja.ReportProcessor.PerformOutput()
   at CrystalReportsNinja.ReportProcessor.Run()
04-08-2020	16:13:28	====================================================================

**Comment by mhertzfeld** [comment]
I will try to look at this in the coming days.  Which version of Ninja are you running?

Instead of electing no output, can you try to run with PDF to a local directory where you have write access, like my documents?  I'm curious as to whether there is a bug when no output path or export type is given in the parameters.

**Comment by charlesgroce** [comment]
Unfortunately I'm already outputting to a subdirectory of the My Documents directory.   The error message when an output path is specified is

04-08-2020	15:40:31	===================Logs and Errors =================================
04-08-2020	15:40:31	Message: Object reference not set to an instance of an object.
04-08-2020	15:40:31	HResult: -2147467261
04-08-2020	15:40:31	Data: System.Collections.ListDictionaryInternal
04-08-2020	15:40:31	Inner Exception: 
04-08-2020	15:40:31	StackTrace:    at CrystalDecisions.CrystalReports.Engine.FormatEngine.ExportToStream(ExportRequestContext reqContext)
   at CrystalDecisions.CrystalReports.Engine.FormatEngine.Export(ExportRequestContext reqContext)
   at CrystalDecisions.CrystalReports.Engine.FormatEngine.Export()
   at CrystalDecisions.CrystalReports.Engine.ReportDocument.Export()
   at CrystalReportsNinja.ReportProcessor.PerformOutput()
   at CrystalReportsNinja.ReportProcessor.Run()
04-08-2020	15:40:31	====================================================================

I'm running Ninja version 1.4.0.0 64-bit.

Thanks!

**Comment by charlesgroce** [comment]
Just following up.  Any advice as my project approaches the need to automatically print Crystal Reports from the command line?

**Comment by mhertzfeld** [comment]
Please post the parameters you are using when running ninja.

**Comment by fabian-sta** [comment]
You need a later version of the CRExport.exe
Attached is the latest Build I have v1.5.1.0
[CRExport.zip](https://github.com/mhertzfeld/CrystalReportsNinja/files/5126771/CRExport.zip)
Current CRExport VER-1.5.1.0 - Needs CRruntime 13.0.25+

**Comment by mhertzfeld** [comment]
Good catch fabian.

Looks like there's even a 1.6 release I haven't compiled and posted yet.

I really need to get back into this project.  If everything goes as planned I am going to boot up my dev enviroment this week and start cleaning things up and adding some of the code from the other branches from the main project.  I was recently laid off from my job and my child is starting school soon, so I should have some free time to spend on this project.

**Comment by mhertzfeld** [comment]
@charlesgroce did the version @fabian-sta recommended help with your problem?

**Comment by charlesgroce** [comment]
Thanks for the follow up @mhertzfeld  and @fabian-sta   I'm not clear what I should do with the provided CRExport.exe.  I would still very much like to get this working :)

**Comment by mhertzfeld** [comment]
Disregard the CRExport.exe.  Download the latest release in the link below and try again.  The problem you are having may have already been addressed in this new release.

Delete all the files in the directory that you are currently using for the ninja program OR create a new directory and extract the the files there.  Make sure that your Crystal Report Runtimes are updated to SP28.

If you are still having problems please post the error.

https://github.com/mhertzfeld/CrystalReportsNinja/releases/tag/v1.7.0.0

**Comment by charlesgroce** [comment]
@mhertzfeld Below are the results:

**Command:**
CrystalReportsNinja -U sa -P PASSWORD -S yellow -D DATABASE -F JobTicket2.rpt -O FINI-340738-JT2.pdf -a "JobNumber:FINI-340738"


**Output:**
Exception: Missing parameter values.
Inner Exception: System.Runtime.InteropServices.COMException (0x8004100E): Missing parameter values.
   at CrystalDecisions.ReportAppServer.Controllers.ReportSourceClass.Export(ExportOptions pExportOptions, RequestContext pRequestContext)
   at CrystalDecisions.ReportSource.EromReportSourceBase.ExportToStream(ExportRequestContext reqContext)
     
   
**About the report:**  
Confirmed only one parameeter @JobNumber   There is a subreport that also uses this parameter.

**Comment by mhertzfeld** [comment]
I do not see an export type in your command.  Export Type is required.

If you want to export as pdf then you need to add "-e pdf" to your command.

Try that and let me know if you run into any additional problems.

I will need to add a validation in the app to ensure all the required parameters are passed and provide a user friendly error when they are not.

**Comment by mhertzfeld** [comment]
Disregard my previous comment about the export type.  Export type is not a required parameter.

I will continue to look into this for you.

**Comment by charlesgroce** [comment]
@mhertzfeld  Thanks Matt!

**Comment by mhertzfeld** [comment]
Looks like the parameter logging is working, for me at least.

Can you add a "-L" to your command so that it writes a log file then post the contents of the log file (or you can add "-LC" which will write the log output to the command prompt where you are executing ninja)?  There should be a section of the log for "Process Parameters", in that section it should show the parameters in the Crystal Report and the Parameters passed in the command.

**Comment by charlesgroce** [comment]
@mhertzfeld  I adjusted the report to utilize just one SQL connection, to no avail, and have confirmed I'm not having any case problems.   

The report log is below.  I was mistaken, there are two subreports.  When I run the report from within Crystal, it only asks for the single parameter JobNumber and it runs fine (granted that's a different system which does not have Ninja on it).

04-09-2020	13:30:19	
04-09-2020	13:30:19	================== LoadReport, Output File and DB logion ===========
04-09-2020	13:30:20	Report JobTicket2-1conn.rpt loaded successfully
04-09-2020	13:30:20	Output Filename : FINI-340738-JT2.pdf
04-09-2020	13:30:20	Output Format : pdf
04-09-2020	13:30:20	Logged into DATABASE Database on SERVER successfully with User id: sa
04-09-2020	13:30:20	
04-09-2020	13:30:20	================== ProcessParameters ===============================
04-09-2020	13:30:20	Number of Parameters detected in the report = 4
04-09-2020	13:30:20	Number of Parameters passed by the users script = 1
04-09-2020	13:30:20	
04-09-2020	13:30:20	Applied Parameter '@JobNumber' as MultiValue 'False'
04-09-2020	13:30:20	
04-09-2020	13:30:20	Skipped '@JobNumber' as MultiValue 'False' Parameter in SubReport = 'ShippingDate' as its Linked to Main Report
04-09-2020	13:30:20	
04-09-2020	13:30:20	Skipped 'CompNumber' as MultiValue 'False' Parameter in SubReport = 'UDFList' as its Linked to Main Report
04-09-2020	13:30:20	
04-09-2020	13:30:20	Skipped 'JobNumber' as MultiValue 'False' Parameter in SubReport = 'UDFList' as its Linked to Main Report
04-09-2020	13:30:20	
04-09-2020	13:30:20	
04-09-2020	13:30:20	================== STEP = PerformOutput ============================
04-09-2020	13:30:20	
04-09-2020	13:30:20	===================Logs and Errors =================================
04-09-2020	13:30:20	Message: Missing parameter values.
04-09-2020	13:30:20	HResult: -2147215870
04-09-2020	13:30:20	Data: System.Collections.ListDictionaryInternal
04-09-2020	13:30:20	Inner Exception: System.Runtime.InteropServices.COMException (0x8004100E): Missing parameter values.
   at CrystalDecisions.ReportAppServer.Controllers.ReportSourceClass.Export(ExportOptions pExportOptions, RequestContext pRequestContext)
   at CrystalDecisions.ReportSource.EromReportSourceBase.ExportToStream(ExportRequestContext reqContext)
04-09-2020	13:30:20	StackTrace:    at CrystalDecisions.ReportAppServer.ConvertDotNetToErom.ThrowDotNetException(Exception e)
   at CrystalDecisions.ReportSource.EromReportSourceBase.ExportToStream(ExportRequestContext reqContext)
   at CrystalDecisions.CrystalReports.Engine.FormatEngine.ExportToStream(ExportRequestContext reqContext)
   at CrystalDecisions.CrystalReports.Engine.FormatEngine.Export(ExportRequestContext reqContext)
   at CrystalDecisions.CrystalReports.Engine.FormatEngine.Export()
   at CrystalDecisions.CrystalReports.Engine.ReportDocument.Export()
   at CrystalReportsNinja.ReportProcessor.PerformOutput()
   at CrystalReportsNinja.ReportProcessor.Run()
04-09-2020	13:30:20	====================================================================

**Comment by fabian-sta** [comment]
I would simplify your report and test
I would export out the sub reports and then run each report individually with the required parameters
Even make a copy of your report and delete all the sub reports and test just a basic output to text
Looks like the problem might be related to how the sub report parameters are being handled.
Maybe don't link the values to the main report and then specify the values from the command line??

**Comment by charlesgroce** [comment]
Solution found!  After taking your recommendations I simplified the report to bare bones and it still wouldn't run.  Then I notice the logged message "Applied Parameter '@Jobnumber' as MultiValue 'False'" and wondered if this meant the engine couldn't determine what this parameter was for so it was defaulting to a generic boolean type with a value of False.  All I needed to do was insert @ as a prefix in front of the parameter and it ran successfully:  

CrystalReportsNinja -U sa -P PASSWORD -S SERVER -D DATABASE -F JobTicket2.rpt -O FINI-340738-JT2.pdf -a "@JobNumber:FINI-340738"

This isn't shown in your documentation at the present time.

Thank you so much for your assistance!

**Comment by fabian-sta** [comment]
Thanks for the update
Not sure about the parameters in your report.. but the parameter values have to be exactly what is listed (Case Sensitive as well from memory)
So if it says @ABc or Item-No: or ABSd@ etc in the report on the Parameter Fields Tab, it has be be identical in the command line

**Comment by mhertzfeld** [comment]
@charlesgroce glad you figured it out.  Closing.
