### ISSUE TITLE
Object Reference not set to an instance of an object

### ISSUE THREAD

**Issue by ljkern** [mhertzfeld/CrystalReportsNinja#3]
Tried your solution. Installed Crystal Runtime 32 bit  build 13.0.22 and your 32 bit version of the Ninja App. Sadly, it did not work. Got an exception: Object Reference not set to an instance of an object. Any idea what would cause this? Running Windows 10 64 bit

**Comment by mhertzfeld** [comment]
What format are you attempting to export?

Can you give me a sample of the command string you are using to execute ninja?

Do you happen to have the full exception/error?
