### ISSUE TITLE
Using ODBC

### ISSUE THREAD

**Issue by mattvester** [mhertzfeld/CrystalReportsNinja#58]
How do you use an ODBC connection in the command line call?
I've tried: CrystalReportsNinja -U username -P password -S ODBC. 

When the the script runs, it comes back with Database logon failed.

**Comment by mhertzfeld** [comment]
-S should be your ODBC DSN name

Make sure the ODBC DSN you are using matches the architecture of the version of Ninja you have installed.  32bit DSN for 32bit Ninja, 64 bit DSN for 64bit ninja.
