### ISSUE TITLE
Parameter File

### ISSUE THREAD

**Issue by mhertzfeld** [mhertzfeld/CrystalReportsNinja#6]
Add functionality so that users can use a file for parameters.

https://github.com/rainforestnet/CrystalReportsNinja/issues/26

**Comment by mhertzfeld** [comment]
I am addressing this by adding the ability to run ninja using powershell scripts.  See version  1.4.0.0

**Comment by fabian-sta** [comment]
A default config file has now been added to the project.. which should resolve this for most
You could use separate folders with individual .exe and .config files for different DB's etc
